title: SkynetXBT Documentation
description: Comprehensive documentation for the SkynetXBT agentic framework
theme: just-the-docs

url: https://skynetxbt.github.io

aux_links:
  GitHub Repository: https://github.com/spheronFdn/skynetxbt
  
# Enable search
search_enabled: true

# Navigation structure
nav_sort: case_insensitive

# Enable collections for better organization
collections:
  user_docs:
    permalink: "/:collection/:name/"
    output: true
  developer_docs:
    permalink: "/:collection/:name/"
    output: true

# Footer
footer_content: "Copyright &copy; 2024 SkynetXBT. Licensed under the MIT License."
