title: SkynetXBT Documentation
description: Comprehensive documentation for the SkynetXBT agentic framework
theme: just-the-docs

url: https://skynetxbt.github.io

aux_links:
  GitHub Repository: https://github.com/spheronFdn/skynetxbt
  
# Enable search
search_enabled: true

# Navigation structure
nav_sort: case_insensitive

color_scheme: nil
color_scheme_toggle:
  enabled: true

# Customize colors for dark mode (optional)
# You can also create custom color schemes
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: red

# Enable collections for better organization
collections:
  user_docs:
    permalink: "/:collection/:name/"
    output: true
  developer_docs:
    permalink: "/:collection/:name/"
    output: true

# Footer
footer_content: "Copyright &copy; 2024 SkynetXBT. Licensed under the MIT License."
